### PR TITLE
deployment: add note about database names and deployment names

### PR DESCRIPTION
**Pull request by ndushay**
bumped into this problem with digital stacks.  Capistrano apparently defaults to the stage name as the database name ...

### CODE REVIEW

**Comment by jkeck** [comment]
I don't think I quite understand.  We typically don't use the stage name as the database name, do we? (i.e. `SearchWorks` db name is actually `blacklight`, not `production`).

**Comment by darrenleeweber** [comment]
AFAIK, the `RAILS_ENV` or `RACK_ENV` value determines the lookup for `config/database.yml`.

**Comment by mjgiarlo** [comment]
This PR seems to have stalled a bit. @ndushay: do you care to take this up again?

**Comment by SaravShah** [comment]
@ndushay  do you care to update this PR, or can we close it?

**Comment by jcoyne** [comment]
Stale. Please reopen if you think we want it.

**Pull request closed without merging**
