### PR TITLE
Update howto_readme.md

### PR DESCRIPTION
**Pull request by darrenleeweber**
Attempting to integrate commentary on #42 into this PR; please review and modify as required.

### CODE REVIEW

**Comment by mejackreed** [comment]
I would :+1:  this... One future addition could be a continuous integration readme which could handle the details for these things. :question:

**Comment by darrenleeweber** [comment]
Maybe the consul link for gemnasium could be replaced with some of the actual consul content, e.g.

- Gemnasium
  - Make sure your app is registered with the sul-dlss gemnasium account.
  - Once it's registered, the gemnasium web interface will display an updated alerts to take action on.
  - Gemnasium does give you a solution when it issues an alert, usually to update your gem to the latest version.

**Comment by bess** [comment]
:+1:

**Comment by cbeer** [comment]
:ok_hand: I'm not thrilled at linking to consul, and agree that replacing it with the relevant content is a good idea.

**Comment by jmartin-sul** [comment]
:+1:

**Comment by darrenleeweber** [comment]
Replaced the consul link with the content in the latest commit on this PR (the github UI actually worked).

**Pull request merged**
