### PR TITLE
Docs to set up sidekiq init script

### PR DESCRIPTION
**Pull request by tallenaz**
When we use sidekiq in a rails project, we should configure rails and
puppet to set up a sidekiq init script so that sidekiq will start on
boot. Otherwise, reboots will require developer attention to make sure
sidekiq is running.

### CODE REVIEW

**Comment by jkeck** [comment]
👍

**Comment by darrenleeweber** [comment]
Sounds like a good idea.  One problem that I encountered resulted in really confusing behavior in the background jobs - let me explain what happened and why it's relevant here.

- capistrano-sidekiq creates and monitors it's own sidekiq-PID file
- sidekiq also provides rake tasks and they also create and monitor their own sidekiq-PID file
- these two ways to control sidekiq are oblivious to one another - so there can be multiple sidekiq-PIDs

When there are more than one sidekiq running, there are race conditions between them to pick up the latest job on the job queue; that is, both processes share the same redis job queue.  When this happens, it can be difficult to track which process has handled the queued job and whether or not it completed successfully.

This is relevant here because the capistrano and puppet systems might generate multiple sidekiq processes, unless they both use the same PID file.  If they use the same PID file, there might be exceptional circumstances where the puppet-check schedule just happens to coincide with a deployment and capistrano removes the PID file that puppet is watching (temporarily).  If that happens, there is a chance they will race to recreate it.

**Comment by tallenaz** [comment]
That's interesting @darrenleeweber. The init script puppet installs works from the pid files in the capistrano deployment at `current/tmp/pids`. I hadn't known about separate pid files for rake tasks.

**Comment by darrenleeweber** [comment]
For ref, the capistrano-sidekiq PID can be configured, see
- https://github.com/seuros/capistrano-sidekiq/blob/master/README.md#usage

The configs also refer to something called `sidekiq/monit` - maybe that could do the restart on reboot?

My concern about multiple processes might be just wrong, because cap-sidekiq can be configured to run multiple processes:
- https://github.com/seuros/capistrano-sidekiq#different-number-of-processes-per-host
- if multiple processes are run - puppet init script would need to monitor them all?
- maybe restart script can use capistrano to do the restart?

**Comment by darrenleeweber** [comment]
See also https://github.com/seuros/capistrano-sidekiq/issues/51

**Comment by SaravShah** [comment]
@tallenaz hey! is this still up to date? or can we close this?

**Comment by jkeck** [comment]
I believe this is still valid and provides important context.

**Comment by tallenaz** [comment]
@SaravShah it's rebased.

**Pull request merged**
