### PR TITLE
effective Communication: talking to developers addition

### PR DESCRIPTION
**Pull request by ndushay**
tweaking the text for communication.md

If you think this is an improvement, then +1;  if you think it makes it worse, -1.   If you want to make additional changes, perhaps wait until the fate of this PR is known, then create a separate PR with your changes?

### CODE REVIEW

**Comment by jgreben** [comment]
:+1:

**Comment by cbeer** [comment]
:ok_hand:

**Comment by jmartin-sul** [comment]
:+1:

**Comment by mejackreed** [comment]
:ok_hand:

**Comment by ggeisler** [comment]
:ok_hand:

**Comment by azaroth42** [comment]
:+1:

**Comment by drh-stanford** [comment]
:+1:

**Pull request merged**
