### PR TITLE
Create licensing.md

### LINKED ISSUE #4: Licensing best practice
Describe Stanford's licensing requirements, as per: https://consul.stanford.edu/display/dlssdevops/How+to+license+your+code

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #4

### CODE REVIEW

**Comment by ndushay** [comment]
:+1:

**Comment by mejackreed** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1:

**Comment by azaroth42** [comment]
Looking for another +1 ... @jkeck @atz @peetucket ? (If you +1, you can hit the big green button)

**Comment by jkeck** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:+1: for OSS licenses, although I would like to see (a) commentary or reference to Stanford legal information on this topic and (b) options for multiple licenses, esp. where use of a library (gem) has a requirement to include their license in any down-stream projects.

**Pull request merged**
