### PR TITLE
Create best practices page for version control

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mejackreed** [comment]
:+1: This seems to capture the consensus discussed on 4/16

**Comment by ndushay** [comment]
:+1:

**Comment by atz** [comment]
:+1:

**Comment by jkeck** [comment]
:+1:

**Comment by darrenleeweber** [comment]
+1 Although I would like to add concrete *suggestions* about branching practices.  This is what I posted on this topic to the dlss-dev list below and the question is whether to include something about it in this document or create anther or additional documents for this topic?

See
http://datasift.github.io/gitflow/IntroducingGitFlow.html
http://datasift.github.io/gitflow/GitFlowForGitHub.html

Key points:

- enhancements are in feature branches (off the develop branch)
  - push/pull feature branches with a github origin
- github pull requests merge a feature branch into the develop branch
  - don't accept your own pull requests (unless you have to)
- the develop branch is deployed to -dev systems (continuously)
  - feature branches may be broken, but develop should be passing unit tests (at least)
- the release branch is deployed to -stage systems for integration testing
  - release branch is named with a release version
  - any -stage bug fixes are in bug-fix branches off the release branch
  - bug-fix branches may be merged into the develop branch as well as the release branch
  - the release branch is continuously deployed to -stage
- once tested and bug-fixed, create a pull request to merge a release into master
  - master is deployed to production
  - release merge into master is tagged in master with the release version

**Comment by azaroth42** [comment]
Please create a new issue.

**Pull request merged**
