### PR TITLE
Summarize prioritization points as best practices

### PR DESCRIPTION
**Pull request by cbeer**
Describing "Best Practices" best practices

### CODE REVIEW

**Comment by ndushay** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1:

**Comment by mejackreed** [comment]
:+1:

**Comment by darrenleeweber** [comment]
+1 but add information about references to additional authorities outside of DLSS, community best practices, to avoid group-think biases and ensure that open-source communities can work with DLSS code.

**Pull request merged**
