### PR TITLE
Update Deployment guidelines

### PR DESCRIPTION
**Pull request by jkeck**
- [x] Update text to clarify that hostnames and user names are not sensitive data.
- [x] Update recommendation on naming capistrano environments.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
While we discussed this at the last developer meeting, @cbeer raised a question about whether `stage` is a reserved word in Capistrano.  Did we get an answer?

**Comment by jmartin-sul** [comment]
FWIW, sul-embed has an environment that it deploys to called `stage`, and that seems to work fine with the version of capistrano it uses (3.4.0, at the moment).

**Comment by darrenleeweber** [comment]
I'm looking at capistrano-sidekiq and the docs contain:
```
:sidekiq_env => fetch(:rack_env, fetch(:rails_env, fetch(:stage)))
```
Note how it uses `fetch(:stage)`.

**Comment by darrenleeweber** [comment]
Reading http://capistranorb.com/documentation/faq/how-can-i-access-stage-configuration-variables/#
where they use `production` and `staging`.  Does this mean that the Capistrano best-practice is to use these "stage" names?

**Comment by jkeck** [comment]
@darrenleeweber: [SUL Embed](https://github.com/sul-dlss/sul-embed) already has a `config/deploy/stage.rb` file and `fetch(:stage)` returns `:stage` in that file.  We have been deploying this way for some time.

As far as I'm concerned, the issue of whether `stage` is a reserved word in capistrano is resolved (no, it is not) and we have proven that we can use `stage` as a deploy environment w/o a problem.

**Comment by mejackreed** [comment]
4 x 👍 ... :shipit: ?

**Pull request merged**
