### PR TITLE
[PROPOSAL] Add initial ruby style guide based on AirBnB's style guide.

### PR DESCRIPTION
**Pull request by jkeck**
I'm adding this as a proposal as I'm not married to the idea of copying this over as our starting point.

I see two ways of approaching this.
1. We start with a copy of another style-guide and modify from there (pulling in upstream changes as necessary).  This gives us a functioning baseline that we can modify and enhance moving forward (however we could get out-of-date if folks aren't tracking the original repository).
2. We simply link to another style guide and layer our own caveats/exceptions (if necessary in addition to that).  This may get unwieldy after some time trying to layer knowledge from one page on-top of another.

Thoughts?  Other approaches?

### CODE REVIEW

**Comment by cbeer** [comment]
> 3) Adopt someone else's style guide without modification. 

I might quibble with a couple things in that guide, but I'm not sure it's worth changing style over. E.g. I'm partial to the rdoc convention for comments (initial `##`), wanting only Ruby 1.9 style hashes, etc.

**Comment by tingulfsen** [comment]
Personally I've never found style guides all that useful, since they tend to focus on very low level code layout details. Unless you think DLSS currently has a problem with different coding styles, I'd rather leave out style guides completely and add things that are a little more high level. For example, I think a convention such as Joe suggested for commenting pinned gems would be a good candidate. Another good one to stick in there would be the various ways to deal with configuration files that are not in Git - see the email thread from earlier this week.

**Comment by mejackreed** [comment]
Ok so I have been thinking about this a bit. @tingulfsen raises a good point about low level details, yet I still think having conventions around this is a good thing. Could a more manageable option be this:

> Use Rubocop to lint your Ruby code

Rubucop by default uses the community [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide)

This gives our team an easy way in to adding consistency across our codebases. When things come up that diverge from the default style guide, we can document those individually and then have a dlss `rubocup.yml` that reflects these changes.

I'm happy to submit this in a counter proposal. Also I'm more or less indifferent on **which** style guide we pick, just that we should be doing things similarly and it should be easy to use (a linter like Rubocop that integrates into a variety of text editors).

**Comment by cbeer** [comment]
:+1: to Rubocop (as long as we disable or up the line length requirement..)

**Comment by jkeck** [comment]
Also, for those that are interested in automating other style enforcement, we're beginning to use HoundCI for scss, js, and ruby linting in [SUL Requests](/sul-dlss/sul-requests).

I'm hoping this process will give us a good set of rubocop, jshint, and scss-lint config files that we can share so that others can think about adopting these same enforcements.

RuboCop is currently the only one that will fail our CI build, but the HoundCI service does comment on diffs that contain violations for any of the configured languages.

**Comment by tingulfsen** [comment]
Sounds good, I'm on board.

**Comment by darrenleeweber** [comment]
+1 for linting plugins, esp. anything that works with sublime text 3.

**Comment by jkeck** [comment]
It's been a week and it appears this doesn't seem to have gained traction.  I have submitted an alternate proposed PR #9 for consideration.

**Comment by azaroth42** [comment]
Dead

**Pull request closed without merging**
