### PR TITLE
Add three practices for releasing gems

### PR DESCRIPTION
**Pull request by cbeer**
Add sections for Semantic Versioning, Bundler tasks, and Adding the DLSS service account as a gem owner

### CODE REVIEW

**Comment by jkeck** [comment]
:+1:

**Comment by tingulfsen** [comment]
:+1:

**Comment by mejackreed** [comment]
:+1:

**Comment by ndushay** [comment]
:+1:

**Comment by jgreben** [comment]
:ok

**Comment by darrenleeweber** [comment]
:+1:  (although this was resolved before I had a chance to review it :-1: )

**Pull request merged**
