### PR TITLE
Create deployment best practices document

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mejackreed** [comment]
:+1:

**Comment by jkeck** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1:

**Comment by jmartin-sul** [comment]
:+1: 

FWIW: i recall some dissent regarding whether hostnames should be considered sensitive info (i think @atz has made the argument that they're almost public info?).  could be worth acknowledging that they're likely less sensitive than user names, passwords, keys, etc.  but that's a pretty minor quibble.

**Comment by eefahy** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:ok_hand: because it may not yet cover everything in https://consul.stanford.edu/x/4TJJC

**Comment by drh-stanford** [comment]
:+1: i like the `Dotenv` way of prompting for hostnames

**Comment by ndushay** [comment]
:+1:    

At some point I intend to change "users" to "userids" and add "passwords" and maybe put them in italics or something - noting here for memory jog.

**Comment by bess** [comment]
:+1:

**Comment by ggeisler** [comment]
:+1:

**Comment by darrenleeweber** [comment]
So what happens now to my comments about the releated consul documents?

**Comment by cbeer** [comment]
@darrenleeweber  I presume we'll migrate such documentation into the playbook as is useful, timely, or when someone feels so moved.

**Comment by darrenleeweber** [comment]
@cbeer - OK, noting this proposal in #45 to keep track of it.

**Pull request merged**
