### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by darrenleeweber**
Ensure that community beyond DLSS is a consideration in developing best practices.

### CODE REVIEW

**Comment by cbeer** [comment]
-0. I think we would be wise to focus on areas of existing consensus and try to document those practices. I'm nervous that requiring an appeal to community authority could distract us from that goal, although I agree that community practice should be an important part of reaching consensus around our local practices.

**Comment by ndushay** [comment]
:-1:  I am MUCH more interested in getting consensus within DLSS;  I think our playbook is for US, now.  

I think we are all aware of other OSS communities and can revise our playbook in the future if we find it conflicts with other communities.

**Comment by darrenleeweber** [comment]
http://en.wikipedia.org/wiki/Groupthink

**Comment by azaroth42** [comment]
:-1: We're trying to establish a catalog of current working practices, regardless of where they came from. Requiring external validation doesn't fit in to that goal, but links to external resources should be encouraged.

**Comment by cbeer** [comment]
Bulk closing inactive issues. Feel free to reopen as needed.

**Pull request closed without merging**
