### PR TITLE
DLSS projects should use the Bootstrap framework for front-end interfaces

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by ggeisler** [comment]
:+1:

**Comment by jkeck** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:-1 because UI frameworks are evolving fast with many abstraction layers possible.  To confine development to one particular framework could limit exploration and creativity; consider alternatives and why they might be useful, i.e. http://modernweb.com/2014/02/17/8-bootstrap-alternatives/.  Does this policy ignore current frameworks in legacy projects that already serve a purpose and need to be maintained?  If this were accepted, would it entail that legacy projects are migrated to a new platform and what purpose would that serve?

**Comment by azaroth42** [comment]
> Does this policy ignore current frameworks in legacy projects that already serve a purpose and need to be maintained? If this were accepted, would it entail that legacy projects are migrated to a new platform and what purpose would that serve?

No decision or description of working practices has any bearing on legacy projects.  It's intended to promote future consistency, not to create practically infinite amounts of retroactive technical debt.

**Comment by cbeer** [comment]
I don't believe this policy limits exploration. As with all such policies, the goal is to provide a starting point, reasonable default option, or a place to begin the conversation. Recording this decision, I believe, indicates to existing and new DLSS developers that Bootstrap is a good enough choice for many projects and we have some existing expertise with the framework across a wide variety of projects.

**Comment by darrenleeweber** [comment]
@azaroth42 says "No decision or description of working practices has any bearing on legacy projects. It's intended to promote future consistency, not to create practically infinite amounts of retroactive technical debt." and also says that the playbook is to document current practices.  I'm confused.

**Comment by darrenleeweber** [comment]
Does it entail, for example, that a job description for a DLSS UI dev position requires 'Bootstrap' experience?

**Comment by azaroth42** [comment]
No, it's for when the new UI developer comes on board and needs to create a new project with no background requirements for tools, and hence provides guidance on what has worked for the department in the past, what they are likely to find support for with other team members, and what is known to be deployable via the regular process.

I think we need a framing document that collects this together. Will propose (yet another) issue for it

**Comment by darrenleeweber** [comment]
I could find something a bit more generic acceptable, i.e. any mature, widely adopted UI frameworks (not a prescription for one very particular UI framework).  One concern is that UI frameworks are often combined, so any requirement on one could have implications for using others (considering complex dependency trees).  So, does the use of Boostrap prevent the use of significant UI/App frameworks that are in wide use?

**Comment by jkeck** [comment]
@darrenleeweber 

1) We currently have **several** projects that use Bootstrap.
2) If you are starting a project and would like to deviate from that practice, you should document why that is the case.  Nobody is saying that everybody  **MUST** use bootstrap, but when you decide not to, it should be a conscious decision and there should be reasoning behind it.
3) If, organically, there becomes a consensus that other frameworks are more desirable or acceptable then that change would be reflected in this document with an appropriate proposal.

Experimentation is all fine and good, but one of the many goals in all of this process is to help developer sustainable software.  As a department, we simply cannot sustain application in N number of different UI frameworks.

**Comment by ggeisler** [comment]
@darrenleeweber Starting a new DLSS project with some "mature, widely adopted UI framework" that is not Bootstrap -- without a good reason besides personal preference -- makes it more difficult for other developers to work on that project (given the large majority of our newer apps use Bootstrap and at least a good handful of us have considerable knowledge of that framework), and makes it more difficult to achieve look-and-feel consistency we're aiming for in common areas of our apps (e.g., SUL header, feedback form, SU global footer. etc.).

**Comment by darrenleeweber** [comment]
I reserve the right to dissent, esp. if all I see is a lot of +1 comments only from those who all drink the cool aid already ;-)  How does this proposal sit with other Apps in DLSS, such as Revs, Argo, and the SDR app?  I have worked on the dlss/sdr-services-app (a sinatra app) and it does use some bootstrap, but I don't recall that the purpose was to provide SUL branding for it.

**Comment by jkeck** [comment]
Absolutely, I'm just trying to help address some of your concerns.

FWIW, Blacklight uses Bootstrap so any Blacklight app (since Blacklight 4.0, released in 2012) is already using Bootstrap.  That includes Revs, the SDR app, and Argo (once the update in-progress is complete).

**Comment by azaroth42** [comment]
Okay, enough please, Darren. That question has already been answered. You have dissented and it has been noted and responded to. Again, the process is intended to gauge consensus, and clearly there is not unanimous agreement on this particular issue. We have the process to ensure that there is at least clarity in how the consensus was determined, rather than to argue indefinitely.  If there are further disagreements in the coming week, then clearly there isn't sufficient agreement to record it.

**Comment by azaroth42** [comment]
:+1: (FWIW)

**Comment by darrenleeweber** [comment]
This discussion has clarified the scope and the current practices, which is a useful discussion.  (Perhaps some of these comments that help to further explain the use and rationale for Bootstrap might be incorporated into the subject document.)

**Comment by cbeer** [comment]
I've amended the introductory sentence as follows:

> When building front-end interfaces, we should use [Twitter Bootstrap](http://getbootstrap.com/) to provide a base layout, common user interface components, and easily sharable SUL branding and look and feel across DLSS projects.

I hesitate to add too much additional verbiage at the beginning, but certainly welcome refinements. I've heard several people express a distaste for pull-requests-against-pull-requests, so I'd suggest sending pull requests to change the language after this is merged. 

@darrenleeweber did the conversation address your concerns, at least to the point where you can live with it, or are you still dead-set against it?

**Comment by darrenleeweber** [comment]
Most of my concerns have been addressed, that is (a) it's not binding and doesn't limit exploration and creativity or, even, well reasoned deviation, (b) the Bootstrap framework is a mature library that is already widely used, and (c) it is used in the OSS effort on Blacklight, which forms the base for a lot of SUL projects.  I hope the document notes about how to customize it are sufficient.  I also wonder whether there are common packaging practices that go along with this and whether this document covers that.  Perhaps these latter concerns are another PR (although I'm not qualified to create it).  So, yes, I can live with it.

**Comment by eefahy** [comment]
:+1:

**Comment by azaroth42** [comment]
Not sure that should have been merged quite yet! People should feel free to disagree (with reason, if it's important to them) until 5/28 according to current process.
(Perhaps a refinement to the process is needed to allow the week to be short circuited if there is an actual majority, but then we'd need to know a majority compared to what?)

**Comment by eefahy** [comment]
Ah right, sorry. I thought the rules were once we get the 4 :+1: s the PR could be merged and could be reopened on dissent but that was a clear misunderstanding. Shall I revert the commit and restore the branch?

**Comment by cbeer** [comment]
I'd suggest what's done is done (or, I'm not sure it's worth the effort to back it out and start a fresh discussion on another pull request). If someone has strong feelings against this proposal, we can sort it out if and when they make themselves known.

**Comment by azaroth42** [comment]
Agree - no need to revert unless necessary.

**Pull request merged**
