### PR TITLE
Adding background processing proposal.

### PR DESCRIPTION
**Pull request by tingulfsen**

### CODE REVIEW

**Comment by darrenleeweber** [comment]
Add links to `Sidekiq` information, like:
- http://sidekiq.org/
- https://github.com/mperham/sidekiq
- https://github.com/mperham/sidekiq/wiki
  - https://github.com/mperham/sidekiq/wiki/Best-Practices

It can help use the redis-namespace gem, i.e
- https://rubygems.org/gems/redis-namespace/

**Comment by mjgiarlo** [comment]
@darrenleeweber makes some good suggestions -- it would be *nice* to at least link to Sidekiq once. I'm happy to see this merged without those changes, though, so either way I'm :+1: on this PR.

**Comment by drh-stanford** [comment]
As mentioned in the intro we use Resque for the DOR workflow framework. So, it'd be nice to add a blurb section about Resque.

Here's what Willy and I wrote up about it at the time we implemented it -- see https://consul.stanford.edu/display/dlssdev/Resque+evaluation

> Resque is a Ruby application with a companion Sinatra-based monitoring web app. It uses Redis as its backend for managing the queues. Each queue is a multivalued record (a List data structure) in Redis and Redis handles all the queueing issues like concurrency, etc.
Resque workers poll one or more queues to get work. For each job they receive, they fork a process to run the job using the self.perform(*args) method. You can run multiple workers per queue if you want to have concurrent jobs for a queue. 

Otherwise I'm 👍

**Comment by darrenleeweber** [comment]
One question that arose during the developer discussions was related to creating multiple queues with various priorities.  It may help to link to the Sidekiq advanced-options page for this information, see https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues

**Comment by darrenleeweber** [comment]
With regard to redis conflicts, here is an example config file that avoids conflicts by using namespaces and different db numbers (this file is similar to a `config/database.yml` file, but it's called `config/redis.yml`):

```yaml
development:
  namespace: dpn-dev
  host: localhost
  port: 6379
  db: 0
  password:

test:
  namespace: dpn-test
  host: localhost
  port: 6379
  db: 1
  password:

production:
  namespace: dpn-prod
  host: localhost
  port: 6379
  db: 2
  password:
```

**Comment by mjgiarlo** [comment]
@darrenleeweber Do you have a sense of the trade-offs of using namespaces vs. dbs for effective segmentation of a Redis instance into different spaces, and what it gets you to use both strategies simultaneously? Just curious -- I haven't made use of dbs before, though I briefly considered it for Hydra-in-a-Box (for multi-tenancy purposes), and there's time to revisit that.

**Comment by darrenleeweber** [comment]
@mjgiarlo - great question and my best guess is that the db number is a better segregation than a namespace.  As I understand it, you can have multiple namespaces in the same db number.  When I use the `redis-cli` to check some `keys *` on a store, I see that a namespace seems to amount to a common prefix on the keys, like `{namespace}:{key}`.  AFAIK, there is no visibility of a namespace across db numbers.  At the risk of streching concepts a bit, the analogy might be something like:
- `redis-db-number == mysql-db`
- `redis-namespace == mysql-table`

**Comment by darrenleeweber** [comment]
FYI, I just ran into a catch with using capistrano to control sidekiq.  There are capistrano options to control sidekiq processes and I switched the number of processes from `2` back to the default (1) at https://github.com/dpn-admin/dpn-sync/blob/master/config/deploy.rb#L61 before I did the next deployment.

A consequence of this was that a ‘rogue’ sidekiq process was left running with a PID file in 
`tmp/pids/sidekiq-1.pid` and capistrano did not go looking for this process to stop it (it did stop the process with PID at `tmp/pids/sidekiq-0.pid`).

So it was happily running old code from a previous deployment in a 'rogue' process.  The old code was pulling jobs off the queue at irregular intervals, whenever it was able to beat the new code to the queue.  The behavior in the app looked like some jobs just went MIA :disappointed:

Lesson learned:  run `cap {target} sidekiq:stop` before changing any of the sidekiq parameters for capistrano.

**Comment by darrenleeweber** [comment]
Add a mention for https://github.com/seuros/capistrano-sidekiq and similar deployment gems for background jobs and related monitoring gems that can restart the background process.

**Comment by darrenleeweber** [comment]
My latest count is 4 x :+1: and I think that's enough.  Most of my comments have been adopted or were incidental.  If I find additional information to provide, I'll do so later.  Going to :ship: this one.

**Pull request merged**
