### PR TITLE
Add waffle.io badge to the README

### LINKED ISSUE #33: Waffle board to facilitate voting
I made a waffle board:
    https://waffle.io/sul-dlss/DeveloperPlaybook

So people can easily see which issues need votes, which have hit the two -1s and need discussion and/or closing.  Can just as easily take it down if it's not useful... +1s / -1s?

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #33

### CODE REVIEW

**Comment by cbeer** [comment]
I don't like that it says "Votes Wanted", but it matches the waffle board and I can't think of a better, concise word. I'm happy to either :ship: it and rephrase it later, or change the text if someone offers better wording.

**Comment by ggeisler** [comment]
:+1:

**Comment by jkeck** [comment]
:+1: 

Perhaps `Needs Votes`?  That way it reads `Needs Votes | 5` indicating there are 5 things that need votes rather than `Votes Wanted | 5` indicating that there are 5 votes wanted.  I could go either way though, I think everybody will know what it means.

**Comment by jmartin-sul** [comment]
:+1:

What about "Voting Needed" or "Voting Needed On"?  Maybe if "vote" isn't plural, it'll seem less like the count is about the number of votes.

Also totally fine with either of the other proposed wordings.

**Comment by azaroth42** [comment]
:+1:
Also, as previously, they're less "votes" and it's more a request for further feedback... "feedback wanted" ?

**Comment by darrenleeweber** [comment]
:+1: (anyhow, what's in a title?)

**Comment by azaroth42** [comment]
Don't say that too loud near the metadata department :D

**Comment by drh-stanford** [comment]
:+1:

**Pull request merged**
