### PR TITLE
Document style guide processes and practices

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by cbeer** [comment]
Before merging, I suggest we have a discussion about dlss-cops, now that people have been trying it (and, in some cases, ignoring it) for awhile.

**Comment by mjgiarlo** [comment]
Sounds good to me, @cbeer. The language here stops short of outright recommending DlssCops, I'll say. It's a tool that may be useful in some scenarios, but may be insufficient in others, and I try to unpack that in this PR.

**Comment by mjgiarlo** [comment]
@cbeer I wonder if the language in this PR mightn't be OK already. The guidelines say that DlssCops is a thing that you *may* use as a starting point if you don't already have one, and otherwise don't require or recommend DlssCops. Good enough?

**Comment by mejackreed** [comment]
👌

**Comment by jkeck** [comment]
Ultimately 👍

I think the language around DLSS Cops gives enough leeway.

**Comment by peetucket** [comment]
👍

**Comment by atz** [comment]
The desire to minimize the scope of exceptions is in conflict with the instruction to start exceptions at the file-level.  If we didn't have 1000+ line classes, maybe the difference wouldn't matter, but in practice it does.  I think a developer should be able to `git grep rubocop:disable`.  

If consolidated file-reading is truly indispensable, I could imagine dropping a comment in `.rubocop.yml`.  That being said, this is an improvement over previous state.  Merging.  👍

**Pull request merged**
