### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by darrenleeweber**
As discussed, references to documentation (e.g. getting-started guides) and specific DLSS projects can ease the learning curve.

### CODE REVIEW

**Comment by darrenleeweber** [comment]
See also #34

**Comment by mejackreed** [comment]
Per #34 I'm :+1: ... Should this live in contributing.md alongside #40 ?

**Comment by drh-stanford** [comment]
:+1:

**Comment by bess** [comment]
:+1:

**Comment by jmartin-sul** [comment]
:+1:

**Pull request merged**
