### PR TITLE
top two levels -- a first pass

### PR DESCRIPTION
**Pull request by ndushay**
In the hopes of making future pull requests a bit easier, I took a stab at organizing and listed some topics in READMEs.

### CODE REVIEW

**Comment by mejackreed** [comment]
I'm all about making initial pull requests easier, but my first impression of this is :-1: . Simply, I think the scope of the pull request is to large. By adding so many subsections and changing the structure it removes the ability of these individual items to be discussed separately. I agree wholeheartedly with most of them, yet feel that they should be discussed individually or added when an individual/group puts the energy into documenting them.

I believe we will see more adoption within the department by taking this piecemeal, we most definitely can't implement everything at once. Maybe we can start by adding the individual headings as issues? Then as they are tackled they can be closed with pull requests?

I'll be happy to concede this point if others feel strongly against this. :smile_cat:

**Comment by cbeer** [comment]
@mejackreed if the PR was simplified, say, to just adding the structure without some of the opinionated content, would that meet your approval? I think @ndushay's goal was to put in some framing to make it easier to add more content without stepping on each other or creating duplicate taxonomies.

**Comment by mejackreed** [comment]
Yes I'd be fine with that. Not sure if everyone is aware of what this is based on (I mentioned it in an email) but this structure is loosely based on [guide](https://github.com/thoughtbot/guides)
Their directory structure is something like:

Top level
```
best-practices/
code-review/
protocol/
security/
style/
CONTRIBUTING.md
README.md
```

Within `best-practices`
```
samples
README.md
```
Not saying this is the may it has to be done, or that I agree with the organization, just an approach used elsewhere.

**Comment by azaroth42** [comment]
Overall: I disagree that piecemeal is better than a swift crushing blow that knocks out the majority of issues where we all agree, and provides triage for determining the areas that need dedicated attention.

PR: Structure seems valuable to help focus those discussions. So long as actual content isn't lost, future PRs can reorganize?

**Comment by cbeer** [comment]
I like the thoughtbot directory structure, although it serves as a supplement to https://playbook.thoughtbot.com/. Maybe most of the topics @ndushay is offering would fit nicely into `protocol`?

**Comment by ndushay** [comment]
We have at least one person who has a knack for deciding to do things differently than most of us.  It is hoped the playbook can be a useful tool in helping developers adopt a common DLSS approach.

I’m not that big on working in lock step on all fronts (e.g. I don’t care that much about whether a bracket is after a newline or not).  But I do care about coding practices that lead to software that is easily maintained, shared and understood by others on a team.   

So my concern is to get written docs ASAP for what I think of as crucial:

* automated tools to help us “enforce” things
* testing practices
* documentation practices
* deployment practices
* security

I *do* believe developers joining DLSS often are weak in testing, and need to learn about testing, documentation practices and deployment practices sooner rather than later.  Personally, i don't see "style" as a top level thing.  Plus, it is language specific.  

I am not gonna go to the mat over how the playbook is organized, if it has useful info that can easily be found.  But can we please step back and think about what it is most important to accomplish?  I am not that concerned about style, which seems to be the current focus, for some reason.

If we want to let the organization of the playbook grow organically, I'm good with that.  If Jack and Jessie and Chris are passionate about style cops right now - fine.  But I'd prefer that energy went into documenting best practices for testing and deployment, personally.  And even coding practices, beyond style, that make for easily maintained, shared code.  Styling is a *part* of that.  Perhaps not the most important part.

I didn't think what I proposed here was so "opinionated" -- more of a ticking off of topics that we probably should cover, eventually.   If we want to reject this pull request, and list the topics as issues - fine.  I thought a sort of outline could be helpful;  if it's not, let's reject it.

I'm getting concerned that this method of working on the Playbook is not all that functional at this stage -- we're talking low level stuff before we've agreed on high level stuff like what is most important.  It's great if y'all have teams where everyone is working acceptably alike -- but we're not all in that privileged position.

**Comment by ndushay** [comment]
btw, I'm actually not that fond of the thoughtbot guide organization.    "best-practices"  seems like the point of the whole thing, and I believe our docs should be example rich, inline, whenever possible, along with sample config files for tools like travis, rspec, etc.     Again, at this time I feel we should focus on what DLSS developers most need help with.  Security is important, but is often "no biggie" as many of our apps are back-endy.   protocols are important for services that create protocols, but lots of our apps don't.  You've already heard my thoughts where i think style fits as a topic.   

try to remember what you needed to learn when you arrived at DLSS:
1.  testing testing testing
2.  DLSS infrastructure (perhaps needs to be on consul)
3.  how to organize your code?  etc.

**Comment by mejackreed** [comment]
@ndushay I emphatically agree with you about the importance of these topics. We should probably have PR's in to start to address some of these topics. Maybe doing this in advance of Thursdays meeting would be good to make the meeting more productive? The idea of using issues and assigning them to yourself if you are working on it might help avoid duplicate efforts?

In regards to the classification - I don't really feel strongly. My comment was more on the structure (I should have probably mentioned that better). A directory should have a README.md at the very least within it. That way when you navigate to it within GitHub it is a bit easier to read as the README.md is selected automatically for viewing. I'd be happy to to make a PR to this one if thats helpful.

**Comment by ndushay** [comment]
@mejackreed oh - if we're talking about the structure, and not the classification, I'm okay with a README for every folder -- I only named them something else because we will have a lot of "README" files and thought we might want to easily select among them in a "finder" window without navigating directories. 

I can't take on all the "high priority" topics myself, of course.  I'm not even sure I can or should take on one of them on my own.  I'm starting to feel overwhelmed by this whole approach -- too much typing and miscommunication to even get started on the actual content itself.

**Comment by azaroth42** [comment]
Dead

**Pull request closed without merging**
