### PR TITLE
Updating CONTRIBUTING with practices for editorial changes (fixes #31)

### LINKED ISSUE #31: Non-content PRs should ship on 4 +1s
Updating non content resources, such as links, table of contents,  typos, etc. should not have to wait a week for a fix.  PRs should note whether they're considered to be non-content, and if others disagree, that should be noted in comments.

[Filing as an issue, as blocked by non-merged #21]

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #31

### CODE REVIEW

**Comment by ggeisler** [comment]
:+1:

**Comment by peetucket** [comment]
:thumbsup:

**Comment by jmartin-sul** [comment]
:ok_hand:

**Comment by azaroth42** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:+1: (I actually went one step further, today, by committing a typo fix directly to master :imp: )

**Comment by drh-stanford** [comment]
:+1:

**Pull request merged**
