### PR TITLE
Add language about linking to DLSS examples

### LINKED ISSUE #34: Link to dlss examples
Amend the process to include a recommendation that individual entries in the playbook link to repositories, code or other similar DLSS reference examples of the practice's use.  This will help understanding (newcomers can quickly look to see how it was done in the past for real), and keep us honest as to what we actually do and what we'd like to do.

(From @darrenleeweber at https://github.com/sul-dlss/DeveloperPlaybook/pull/29#issuecomment-105930917)

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #34

### CODE REVIEW

**Comment by ggeisler** [comment]
:+1:

**Comment by peetucket** [comment]
:thumbsup:

**Comment by jmartin-sul** [comment]
:+1:

**Comment by jgreben** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1:

**Comment by darrenleeweber** [comment]
:+1: and I started PR #43 before I saw this, so now I'm not sure whether reiterating the point in multiple places is good or if it's better to refactor for DRY?  With regard to human instructions, the former is better (i.e. reiterate the point).

**Comment by drh-stanford** [comment]
:+1:

**Pull request merged**
